update apis
kk-digital/kcg-ml-image-pipeline pull request #455
Opened 2024-01-06 06:00 UTC by sandrodevdariani

2024-01-06 16:18 UTC, Senyoret1 requested changes

2024-01-06 16:18 UTC, Senyoret1 commented on orchestration/api/api_model.py
> +        return response_handler.create_success_response({"model_types": list(model_types)}, http_status_code=200)
No cache

2024-01-06 16:18 UTC, Senyoret1 commented on orchestration/api/api_tag.py
> -        was_present = False
You removed this var from here and now it is declared only inside the scope of the if, but you are using it outside the if, when returning the answer. Does this compile in python? Because that not valid in other languajes

2024-01-06 16:18 UTC, Senyoret1 commented on orchestration/api/api_tag.py
> +                {"$set": {"tag_count": 0}}
This does not appear to be needed, as you are removing the entry just 2 lines below. What you save here will be erased anyways

2024-01-07 05:48 UTC, sandrodevdariani commented on orchestration/api/api_model.py
> +        return response_handler.create_success_response({"model_types": list(model_types)}, http_status_code=200)
Im sure that there is not any cache operation here, if u talking about the line model_types.add(match.group(1)) it simply adds the extracted model type to the model_types set.

2024-01-07 12:43 UTC, Senyoret1 commented on orchestration/api/api_tag.py
> +            return response_handler.create_success_response({"wasPresent": True}, http_status_code=200)
With this change now you are always informing that the tag was not found, regardless of whether the tag was found or not

2024-01-07 13:21 UTC, Senyoret1 commented on orchestration/api/api_tag.py
> +                "deprecated": updated_category.get("deprecated", False),
What is the `deprecated` property for? I don't see it being used somewhere else. If it is for something, may it not be `true` here?

2024-01-07 15:34 UTC, sandrodevdariani commented on orchestration/api/api_tag.py
> +                "deprecated": updated_category.get("deprecated", False),
brandon told me that we are using deprecated field, we wont delete tag or tag category we just point them as deprecated. I will implement this one into tag scheme as well.

2024-01-07 15:34 UTC, sandrodevdariani commented on orchestration/api/api_tag.py
> +        new_tag_category_id = last_entry["tag_category_id"] + 1 if last_entry else 0
I think tag_category_id and _id are different ones, "_id" generating automatically  from mongo and tag_category_id generating  like that
 0,1,2 and etc.

2024-01-07 16:23 UTC, Senyoret1 commented on orchestration/api/api_tag.py
> +        new_tag_category_id = last_entry["tag_category_id"] + 1 if last_entry else 0
Ok, that is a system design reques, I’ll not review that

2024-01-07 16:25 UTC, Senyoret1 commented on orchestration/api/api_tag.py
> +                "deprecated": updated_category.get("deprecated", False),
If this is for later, it is ok, if it is for now, then it is not implemented, as you are removing the whole record in the delete method and returning deprecated elements in the list mehotd

2024-01-08 13:23 UTC, Senyoret1 approved these changes

2024-01-08 14:01 UTC, merged