add new endpoints for tags
kk-digital/kcg-ml-image-pipeline pull request #471
Opened 2024-01-11 17:16 UTC by sandrodevdariani

2024-01-12 21:41 UTC, Senyoret1 requested changes

2024-01-12 21:41 UTC, Senyoret1 commented on orchestration/api/mongo_schemas.py
> +    tag_string: str = Field(..., description="Name of the tag")
Please add the validation conditions in the description, like "only letters, numbers, hyphens and underescores". This will be shown in the automatic documentation

2024-01-12 21:41 UTC, Senyoret1 commented on orchestration/api/mongo_schemas.py
> +    tag_category_string: str = Field(..., description="Name of the tag category")
Please add the validation conditions in the description

2024-01-13 05:21 UTC, sandrodevdariani commented on orchestration/api/api_tag.py
> +            "deprecated": tag_data.deprecated,
that endpoint is add new tag /tags, so if we input True it will return True. 
I agree that it not logically to add True deprecated tag, but if we dont input anything in this field, default it is false

2024-01-13 05:44 UTC, sandrodevdariani commented on orchestration/api/mongo_schemas.py
> +    tag_category_string: str = Field(..., description="Name of the tag category")
Done

2024-01-13 05:44 UTC, sandrodevdariani commented on orchestration/api/mongo_schemas.py
> +    tag_string: str = Field(..., description="Name of the tag")
Done

2024-01-13 05:44 UTC, sandrodevdariani commented on orchestration/api/api_tag.py
> +    # Prepare update data
Done

2024-01-13 05:44 UTC, sandrodevdariani commented on orchestration/api/api_tag.py
> +        # Create the new tag object with only the specified fields
Done

2024-01-15 20:39 UTC, Senyoret1 requested changes

2024-01-15 20:39 UTC, Senyoret1 commented on orchestration/api/api_utils.py
> +        # Assuming ISO 8601 format (YYYY-MM-DD)
Also allow to use the `yyyy-MM-ddThh:mm:ss` format. Mongodb accepts it and it can be better in some cases.

2024-01-15 20:42 UTC, Senyoret1 requested changes

2024-01-15 20:42 UTC, Senyoret1 commented on orchestration/api/api_clip.py
> +            return response_handler.create_success_response({"clip_vector": vector}, http_status_code=201, headers={"Cache-Control": "no-store"})
What had to be fixed is the documentation, not what the endpoint is returning. Also, not in this line, but no changes were made to `GET /clip/vectors/{phrase}`

2024-01-15 20:50 UTC, Senyoret1 commented
Appart from the comments, the changes for making `GET /clip/server-status` are still needed

2024-01-16 13:53 UTC, merged